# -*- coding: utf-8 -*-
"""字段契约声明表 —— 全系统关于"字段从哪来 / 什么口径 / 何时可用"的单一事实源。"""
from __future__ import annotations

from .schema import FieldContract, ReadyProbe

FIELDS: tuple[FieldContract, ...] = (
    FieldContract(
        name="auc_main_net",
        source="meoz.fundflow_kp",
        source_field="auction_main_net_amount",
        unit="元",
        caliber="竞价主力净额（特大单+大单），9:25 起更新，9:25 定格后即为当日终值",
        ready_after="09:25:35",
        column="auc_main_net",
        consumers=("bid_strength.__compose.ff", "scorer.factors.bid_strength.w_ff"),
        confusion="≠ main_net_amount（盘中全天口径，收盘后为全天值，非零率 97.6%）",
        status="degraded",
        probe=ReadyProbe(
            kind="non_zero_ratio", min=0.19, scope="all_market",
            note="下限 = 旧 NETFILL_MIN_N(1000) / 全市场(≈5209)；盘后实测基线 30.1~32%，校准备忘",
        ),
    ),
    FieldContract(
        name="auc_vol_ratio",
        source="meoz.daily_auc",
        source_field="auc_vol_ratio",
        unit="倍",
        caliber="竞价量比 = 竞价成交量 ÷ 近 5 日平均每分钟成交量（猫爪 openapi 原文定义）",
        ready_after="09:25:35",
        column="auc_vol_ratio",
        consumers=("bid_strength.bid_vol_ratio", "scorer.factors.bid_strength.w_vol_ratio"),
        confusion=("≠ f10（东财量比，全天口径）；旧口径「今 9:25 额 ÷ 昨 9:25 额」已降为"
                   "**历史行/本列缺值时的回退**（bid_strength._fill_snapshot），不是本列语义"),
        status="degraded",
        probe=ReadyProbe(
            kind="non_zero_ratio", min=0.90, scope="all_market",
            note="实测 2026-09-24 猫爪 daily_auc 非零 5474/5567(98.3%)；下限 90% 同时用作"
                 "「拿到猫爪数据再定格」的就绪判定与 09:26 补采的达标线",
        ),
    ),
    FieldContract(
        name="auc_turnover",
        source="self.snapshot",
        source_field="auc_turnover",
        unit="%",
        caliber="竞价换手率",
        ready_after="09:25:20",
        column="auc_turnover",
        consumers=("scorer.factors.activity",),
        confusion="≠ f8（东财全天换手率，时间窗口不同，**不可对拍**）",
        self_computable=True,
    ),
    FieldContract(
        name="seal_amount",
        source="meoz.daily_auc_fd",
        source_field="fa_0925",
        unit="元",
        caliber="9:25 涨停封单额（非涨停股无封单，置 0）",
        ready_after="09:25:20",
        column="bid_buy_amt",
        consumers=("scorer.factors.warn", "check_seal_quality"),
        confusion="screening.fd_amount / fa_0925l 为同义优先源，本字段为其兜底",
    ),
    FieldContract(
        name="free_mv",
        source="meoz.screening",
        source_field="free_float_mv",
        unit="亿",
        caliber="自由流通市值（2026-09-20 主人拍板，门槛/评分统一取此口径）",
        ready_after="09:15:10",
        column="free_mv",
        consumers=("scorer.factors.market", "picker.filter"),
        confusion="≠ circ_mv / float_mv（流通市值，≈自由流通的 2 倍，仅缺失时兜底）",
    ),
    FieldContract(
        name="float_mv",
        source="meoz.valuation",
        source_field="circ_mv",
        unit="亿",
        caliber="流通市值 —— **仅作 free_mv 缺失时兜底 + 前端展示列**",
        ready_after="09:15:10",
        column="float_mv",
        consumers=("scorer.factors.market(fallback)",),
        confusion="≠ free_mv；兜底时阈值偏保守（落更高档→分略低），无害但需知情",
    ),
    FieldContract(
        name="pre_fd_amount",
        source="meoz.screening",
        source_field="fd_amount",
        unit="元",
        caliber="昨日封单额（官方原生值，不换算）",
        ready_after="09:15:10",
        column="pre_fd_amount",
        consumers=("scorer.factors.warn",),
        confusion="东财链路完全无此字段，仅猫爪侧提供",
    ),
    FieldContract(
        name="realtime_fund_flow",
        source="diemeng.realtime",
        source_field="fund_flow",
        unit="—",
        caliber="灵启实时资金流",
        ready_after="09:30:00",
        consumers=(),
        confusion="★ 实测竞价时段（<9:30）返回 **0 条** —— 属市场机制，不是权限问题",
        status="planned",
    ),
)
